updated with my name
acmutd/htf-development pull request #28
Opened 2020-10-17 23:06 UTC by anirranjan

2020-10-18 21:01 UTC, harshasrikara requested changes
Code looks good! Can you change `8123` back to `8079` in the `index.ts` file?

2020-10-21 05:28 UTC, ez314 requested changes
Update on PR

2020-10-21 05:28 UTC, ez314 commented on functions/src/index.ts
> +app.listen(8123);
```suggestion
app.listen(8079);
```

2020-10-21 16:31 UTC, anirranjan commented
I have changed the port from 8123 to 8179.

2020-10-21 16:32 UTC, ez314 approved these changes

2020-10-21 17:11 UTC, harshasrikara approved these changes

2020-10-21 17:20 UTC, merged